### PR TITLE
Match files named Dockerfile

### PR DESCRIPTION
**Pull request by dcecile**

### CODE REVIEW

**Comment by dsherret** [comment]
Thanks @dcecile! This will be released in 0.2.0 once the CI finishes.

**Comment by dcecile** [comment]
Great! :)

Hmm I tried to update to the released 0.2.0, but it's not detecting my `Dockerfile`. I tried using dpring 0.18.1. Was there another place in this repo that needed a change?

Here are the steps using a test repo I created:

```shell
git clone https://github.com/dcecile/dprint-dockerfile-test.git
cd dprint-dockerfile-test
npm install
./node_modules/.bin/dprint check
./node_modules/.bin/dprint output-file-paths
```

(Only `other.dockerfile` is resolved, not `Dockerfile`.)

**Comment by dsherret** [comment]
@dcecile thanks for the reproduction. It was a bug in the CLI and should be fixed now in 0.18.2 (it wasn't properly handling casing).

**Comment by dcecile** [comment]
:smiley: It's working for me now with 0.18.2. Thank you!

**Pull request merged**
